### ISSUE TITLE
Search for code in repos

### ISSUE THREAD

**Issue by krlmlr** [ropenscilabs/ghrecipes#15]
Shortcomings of the built-in search bar on https://github.com:

- No grouping of the results by repo: Often I only want to answer the question "Which repo has code that matches a search string", not list every entry
- Hard to search for special characters, e.g. how to search for code that contains `library(drake)` ?
- only 10 results at a time

From https://twitter.com/ma_salmon/status/978531210338152448.

@jimhester: I vaguely remember you did work along these lines.?

**Comment by jimhester** [comment]
The API code search is not a solution to these problems, your search is restricted to a single repo

**Comment by maelle** [comment]
@jimhester are you referring to how the V3 API handle such search queries?

I've had a look and currently one cannot search for code using the V4 API. 😢 This query here would work for e.g. "type: REPOSITORY" but this is not what we want.

```
{
  search(query: "drake language:r", type: CODE, first: 100) {
    edges {
      node {
        ... on Repository {
          name
          owner {
            login
          }
          description
          url
        }
      }
    }
  }
}
```

I'll try to make a feature request but not too sure they're taking any cf #7 

Maybe using GitHub archive for code tracking purposes is a better idea at the moment. 🤔 My only experience with that tool is [this blog post](http://www.masalmon.eu/2017/12/21/wherehaveyoubeen/). This [example query](https://cloud.google.com/bigquery/public-data/github#how_many_times_this_should_never_happen_appears) searches for a given text in code without filtering for the language but [here](https://cloud.google.com/bigquery/public-data/github#most_commonly_used_go_packages) I see that one could "simply" filter ".r" like they filter ".go".

I was also daydreaming a badge as a way to make use cases available to readers of the docs of a package. If the query were done really well, one could be quite sure the repo contain use cases of the package. There could be a badge in the README of say drake that'd say "click here for live examples, last update XXX-XX-XX". Obviously use cases in the wild are not necessarily the best docs, but maybe it could be useful.

To be continued...

**Comment by maelle** [comment]
Found the related forum discussion https://platform.github.community/t/how-to-search-code-using-graphql/1906/5

**Comment by maelle** [comment]
Archiving this repo as I do not have the opportunity to work on this package at the moment.

https://devguide.ropensci.org/curationpolicy.html#incubator-packages
