### ISSUE TITLE
use graphql "after" parameter for iteration

### ISSUE THREAD

**Issue by mpadge** [ropenscilabs/ghrecipes#18]
Just a thought, but it seems a bit nicer than the current [`iterate` fn](https://github.com/ropenscilabs/ghrecipes/blob/master/R/zzz.R), which is pretty difficult to parse (`select(.!=NULL)[-1]`?). I've done a no-doubt inefficient version in [`stellar`](https://github.com/ropenscilabs/stellar/blob/master/R/stars.R) with `form_qry_start()` and `form_qry_next()` for iteration. This is okay for my one-type-of-query-only idea, but extension to more efficient forms is pretty straightforward, and the benefit is the direct readability of the `pageInfo` parameters. Just a thought - feell free to close if you wanna ignore it for now. Or wait for a bit while I polish this in `stellar`, and I'll get a PR to ya.

**Comment by maelle** [comment]
Thanks a lot! I will have a look next time I really work on this pkg which might be in a couple of weeks

**Comment by maelle** [comment]
@mpadge would you be interested in making a PR to `ghrecipes`? 😉

**Comment by maelle** [comment]
Archiving this repo as I do not have the opportunity to work on this package at the moment.

https://devguide.ropensci.org/curationpolicy.html#incubator-packages
