### ISSUE TITLE
get directly the status of this issue (open or closed)

### ISSUE THREAD

**Issue by cderv** [ropenscilabs/ghrecipes#20]
Currently when using `get_issue_thread` or `get_issue_labels_state`, there is a column `closed_at` to give time and date when the issue was closed. 

It would be nice to have a logical status column to be able to filter directly on this the result. 

It may also be an opportunity (implementation could be unrelated) to offer a status argument to only query opened or closed issue. 

Currently, this status column must be computed. 
Easily in one case because the `closed_at` column as `NA` value. Not so easily in the other case because no `NA` value.

``` r
owner <- "ropenscilabs"
repo <- "ghrecipes"
library(ghrecipes)
library(tidyverse)
# easy case
get_issue_labels_state(owner, repo) %>%
  head() %>%
  mutate(opened = is.na(closed_at)) %>%
  select(number, closed_at, opened)
#> # A tibble: 6 x 3
#>   number closed_at           opened
#>    <int> <dttm>              <lgl> 
#> 1      1 NA                  TRUE  
#> 2      2 2018-03-07 09:24:44 FALSE 
#> 3      3 2018-03-12 09:18:46 FALSE 
#> 4      4 2018-03-26 07:30:16 FALSE 
#> 5      5 NA                  TRUE  
#> 6      6 NA                  TRUE

# need computation
get_issue_thread(owner, repo, 1) %>%
  mutate(opened = str_detect(closed_at, "^9999")) %>%
  select(issue, closed_at, opened)
#> # A tibble: 1 x 3
#>   issue closed_at  opened
#>   <dbl> <chr>      <lgl> 
#> 1     1 9999-01-01 TRUE
# or using date
get_issue_thread(owner, repo, 1) %>%
  mutate(closed_at = lubridate::ymd(closed_at)) %>%
  mutate(opened = lubridate::year(closed_at) == 9999) %>%
  select(issue, closed_at, opened)
#> # A tibble: 1 x 3
#>   issue closed_at  opened
#>   <dbl> <date>     <lgl> 
#> 1     1 9999-01-01 TRUE
```

<sup>Created on 2018-09-27 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

On the last two examples, there maybe some adjustment to do in `get_issue_*` functions to have a common output typed column. Also, the column names are not them same (number vs issue).
Tell me if you want others issues and PR on this.

**Comment by maelle** [comment]
Good idea! Yes, a PR would be great!

**Comment by cderv** [comment]
Ok. In fact I missed the `state` column in `get_issue_labels_state` 🤦‍♂️ 
But this column is not present in the result of `get_issue_thread` as I would have expected. 

So there are two choices here I think for the API:  
1. Add the column to `get_issue_thread` as in `get_issue_labels_state`
2. Let the user do a join operation to get the info, but the key should be the issue number and it would be more practical if column name are the same. 

I am more in favor of 1 but at the end it depends also on how the API can be changed. What are your plan on this ? 

For info, here is the current standard column name return by the two functions:
``` r
library(ghrecipes)
# error 
names(get_issue_labels_state("ropenscilabs", "ghrecipes"))
#> [1] "number"     "created_at" "closed_at"  "title"      "state"     
#> [6] "labels"     "owner"      "repo"
names(get_issue_thread("ropenscilabs", "ghrecipes", 16))
#>  [1] "title"              "author_association" "created_at"        
#>  [4] "closed_at"          "body"               "author"            
#>  [7] "comment_url"        "issue"              "owner"             
#> [10] "repo"
```

<sup>Created on 2018-09-27 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by maelle** [comment]
I think 1. is fine, more logical, easier for the user.

**Comment by maelle** [comment]
Archiving this repo as I do not have the opportunity to work on this package at the moment.

https://devguide.ropensci.org/curationpolicy.html#incubator-packages
