### ISSUE TITLE
Function to pull repos contributed to 

### ISSUE THREAD

**Issue by jsta** [ropenscilabs/ghrecipes#25]
I have this in my fork ([get_contributions](https://github.com/jsta/ghrecipes/blob/jsta_advanced/R/get_contributions.R)). Is it is of enough interest for a PR?

**Comment by maelle** [comment]
Yes! What is your use case btw?

**Comment by jsta** [comment]
From what I can tell `get_repos` only pulls repos that you either "own" or have write access to. This function would allow you to get at repos you've had PRs accepted at but don't have write access.

**Comment by maelle** [comment]
:ok_hand:
