### ISSUE TITLE
get_repos_contributed can only pull the repos of key owner

### ISSUE THREAD

**Issue by jsta** [ropenscilabs/ghrecipes#27]
I am unable to pull the repos contributed to for an arbitrary user. Only the repos for my own key.

**Comment by maelle** [comment]
ah ok then could you make a PR to rename the function with "my" in it and without the username argument? It must be an API limitation? :thinking:

**Comment by jsta** [comment]
Turns out I was wrong. The code as written **can** pull for an arbitrary user. It's just that a non-informative error is thrown when the user has no contributed repos. The same error is thrown by `get_repos` on an account with no repos...

```r
library(ghrecipes)
get_repos("lock")
```
> Error: Column `name` not found in `.data`
Call `rlang::last_error()` to see a backtrace
Called from: abort(msg, "rlang_data_pronoun_not_found")

**Comment by maelle** [comment]
Aaah ok good catch. Interested in a PR?

Btw what happens if you use a non-existing username, e.g. "features" or "issues"?
