### ISSUE TITLE
issue with curl : All headers must be strings

### ISSUE THREAD

**Issue by cderv** [ropenscilabs/ghrecipes#30]
It seems there was a change somewhere that leads to an error. 
```r
get_issue_labels_state("ropensci", "taxize")
#> Error in curl::handle_setheaders(opts$url$handle, .list = opts$headers): All headers must be strings.
```
See examples that errors
https://docs.ropensci.org/ghrecipes/reference/get_issue_labels_state.html

traceback is 
```r
12: stop("All headers must be strings.")
11: curl::handle_setheaders(opts$url$handle, .list = opts$headers)
10: private$make_request(rr)
9: con$get()
8: gh_GET(if (is.null(schema_url)) self$url else schema_url, self$headers, 
       ...)
7: cont(gh_GET(if (is.null(schema_url)) self$url else schema_url, 
       self$headers, ...))
6: jsonlite::fromJSON(x)
5: parze(cont(gh_GET(if (is.null(schema_url)) self$url else schema_url, 
       self$headers, ...)))
4: ghql_gh_cli$load_schema()
3: create_client()
2: iterate(query)
1: get_issue_labels_state("ropensci", "taxize")
```

**Comment by maelle** [comment]
Thanks! I'll investigate, but it might take a while before I get to it.

**Comment by cderv** [comment]
I think this happens because `ghql` switch to `crul` in https://github.com/ropensci/ghql/commit/c24d17cb759cee95616965fe6c77ef00f31f2edc

This is indeed related to https://github.com/ropenscilabs/ghrecipes/issues/9 because I think the header contruction is creating issue
https://github.com/ropenscilabs/ghrecipes/blob/af558876ab4f83786ff1180928489cb9cc954542/R/zzz.R#L49
because replacing by how it is constructed in `crul` (see example in `?GraphqlClient`)
```r
headers = list(Authorization = paste0("Bearer ", token))
```

it could be also be an issue that `crul` does not accept httr's header construct. the `add_headers` will return a httr request object where only `httr::add_headers(...)$headers` is what `crul` expect. 

do you want a PR with the new `list()` instead of `httr::add_headers` ?
