### ISSUE TITLE
Add recipe to get a repo Travis config file

### ISSUE THREAD

**Issue by maelle** [ropenscilabs/ghrecipes#5]
And parse it into a data.frame/tibble like what I currently do for DESCRIPTION in `get_description`

The goal would be to then have a collection of edge cases based on having collected config files from say all rOpenSci packages, all r-lib packages etc.

Cf https://twitter.com/Hao_and_Y/status/968614179254034432

Cc @jhollist @ha0ye

**Comment by maelle** [comment]
A collection would have the issue of non necessarily being opinionated. E.g. there might be several solutions for each system requirement... But then one could filter by one's favourite maintainer?

**Comment by maelle** [comment]
Here is a small example.

``` r
links <- c("jeroen/sodium", "bcgov/rcaaqs", "hypertidy/silicate", 
           "ropensci/osmdata")
links <- stringr::str_split(links, "\\/", simplify = TRUE)
owners <- links[,1]
repos <- links[,2]
configs <- purrr::map2_df(owners, repos, 
                          ghrecipes::get_travis_config,
                          branch = "master")
#> Warning in bind_rows_(x, .id): Unequal factor levels: coercing to character
#> Warning in bind_rows_(x, .id): binding character and factor vector,
#> coercing into character vector

#> Warning in bind_rows_(x, .id): binding character and factor vector,
#> coercing into character vector
#> Warning in bind_rows_(x, .id): Unequal factor levels: coercing to character
#> Warning in bind_rows_(x, .id): binding character and factor vector,
#> coercing into character vector

#> Warning in bind_rows_(x, .id): binding character and factor vector,
#> coercing into character vector
#> Warning in bind_rows_(x, .id): Unequal factor levels: coercing to character
#> Warning in bind_rows_(x, .id): binding character and factor vector,
#> coercing into character vector

#> Warning in bind_rows_(x, .id): binding character and factor vector,
#> coercing into character vector
#> Warning in bind_rows_(x, .id): Unequal factor levels: coercing to character
#> Warning in bind_rows_(x, .id): binding character and factor vector,
#> coercing into character vector

#> Warning in bind_rows_(x, .id): binding character and factor vector,
#> coercing into character vector

#> Warning in bind_rows_(x, .id): binding character and factor vector,
#> coercing into character vector

#> Warning in bind_rows_(x, .id): binding character and factor vector,
#> coercing into character vector

#> Warning in bind_rows_(x, .id): binding character and factor vector,
#> coercing into character vector

#> Warning in bind_rows_(x, .id): binding character and factor vector,
#> coercing into character vector
configs <- dplyr::mutate_if(configs, is.character, stringr::str_squish)
knitr::kable(configs)
```

| package  | repo     | owner     | branch | title                                                             | maintainer                             | dependencies                                                                                                                                                                                                                                                                                                                                                                                                         | system\_requirements    | description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | language | cache    | sudo     | matrix                                                                                                                                                                                                                                                                                                        | r\_github\_packages | addons                                                                                                        | warnings\_are\_errors | notifications                                        | after\_success                                                                                | cran                       | dist   | before\_install                                                                                                                                                                                                             | r                      | r\_packages |
|:---------|:---------|:----------|:-------|:------------------------------------------------------------------|:---------------------------------------|:---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:------------------------|:-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:---------|:---------|:---------|:--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:--------------------|:--------------------------------------------------------------------------------------------------------------|:----------------------|:-----------------------------------------------------|:----------------------------------------------------------------------------------------------|:---------------------------|:-------|:----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:-----------------------|:------------|
| sodium   | sodium   | jeroen    | master | A Modern and Easy-to-Use Crypto Library                           | Jeroen Ooms <jeroen@berkeley.edu>      | Suggests, Suggests, knitr, rmarkdown, *, *                                                                                                                                                                                                                                                                                                                                                                           | libsodium (&gt;= 1.0.3) | Bindings to 'libsodium': a modern, easy-to-use software library for encryption, decryption, signatures, password hashing and more. Sodium uses curve25519, a state-of-the-art Diffie-Hellman function by Daniel Bernstein, which has become very popular after it was discovered that the NSA had backdoored Dual EC DRBG.                                                                                                                                                                                                                                                               | r        | packages | required | list(list(os = "linux", dist = "precise"), list(os = "linux", dist = "trusty", env = "R\_CODECOV=true", r\_check\_args = "--use-valgrind"), list(os = "osx", osx\_image = "xcode8.1", brew\_packages = "libsodium", latex = FALSE), list(os = "osx", osx\_image = "beta-xcode6.4", disable\_homebrew = TRUE)) | jimhester/covr      | list(sources = list(list(sourceline = "ppa:chris-lea/libsodium")), packages = c("libsodium-dev", "valgrind")) | TRUE                  | list(on\_success = "change", on\_failure = "change") | if \[\[ "${R\_CODECOV}" \]\]; then R -e 'covr::codecov()'; fi                                 | NA                         | NA     | NA                                                                                                                                                                                                                          | NA                     | NA          |
| rcaaqs   | rcaaqs   | bcgov     | master | Tools to implement CAAQS analysis for air quality                 | Andy Teucher <andy.teucher@gov.bc.ca>  | Depends, Imports, Imports, Imports, Imports, Imports, Imports, Suggests, Suggests, Suggests, R, lubridate, dplyr, lazyeval, ggplot2, scales, tidyr, sp, rgdal, testthat, &gt;= 3.3.0, &gt;= 1.6.0, &gt;= 0.5.0, &gt;= 0.2.0, &gt;= 2.2.0, &gt;= 0.4.0, &gt;= 0.6.0, &gt;= 1.2, &gt;= 1.2, &gt;= 1.0.0                                                                                                                | NA                      | Analyze air quality data according to Canadian Ambient Air Quality Standars (CAAQS) guidelines.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          | r        | NA       | required | NA                                                                                                                                                                                                                                                                                                            | NA                  | NA                                                                                                            | NA                    | list(on\_success = "change", on\_failure = "change") | NA                                                                                            | <https://cran.rstudio.com> | trusty | sudo add-apt-repository ppa:ubuntugis/ppa --yes, sudo apt-get --yes --force-yes update -qq, sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev                                                  | release, devel, oldrel | NA          |
| silicate | silicate | hypertidy | master | A Common Form for Complex Data                                    | Michael D. Sumner <mdsumner@gmail.com> | Depends, Suggests, Suggests, Suggests, Suggests, Suggests, Suggests, Suggests, Imports, Imports, Imports, Imports, Imports, Imports, Imports, Imports, Imports, Imports, Imports, R, covr, gibble, knitr, rmarkdown, sf, sp, testthat, dplyr, ids, methods, purrr, quadmesh, rlang, RTriangle, decido, tibble, unjoin, viridis, &gt;= 3.3.2, *, &gt; 0.0.2, *, *, *, *, *, *, *, *, *, *, *, *, *, *, &gt;= 0.0.3, * | NA                      | Generate a generic common form of complex data, suitable for conversions and transmission. Many complex data structures are composed of 'paths' (sequentially-linked records) or 'primitives' (basic, component types grouped into higher forms). These two kinds of structure are very common, particularly in spatial data, graphics and analytical structures. The universal model 'SC' is provided that can represent any of these. Another more specialist model 'PATH' is included as as well as tools to switch between these forms, and the component functions for conversions. | R        | packages | required | list(list(os = "linux", r = "release", dist = "trusty", env = c("BUILD\_NAME=trusty\_release", "DETAILS="release build"")), list(os = "osx", r = "release", before\_install = "", disable\_homebrew = TRUE, env = c("BUILD\_NAME=osx\_release", "DETAILS="release build"")))                                  | NA                  | NA                                                                                                            | NA                    | NA                                                   | Rscript -e 'covr::codecov()'                                                                  | NA                         | trusty | sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes, sudo apt-get --yes --force-yes update -qq, sudo apt-get install -y libudunits2-dev libproj-dev libgeos++-dev libgdal-dev, sudo apt-get install -y libv8-dev | NA                     | NA          |
| osmdata  | osmdata  | ropensci  | master | Import 'OpenStreetMap' Data as Simple Features or Spatial Objects | Mark Padgham <mark.padgham@email.com>  | Depends, Imports, Imports, Imports, Imports, Imports, Imports, Imports, Imports, Imports, Imports, Imports, Suggests, Suggests, Suggests, Suggests, Suggests, Suggests, LinkingTo, R, curl, httr, lubridate, magrittr, methods, Rcpp, rvest, jsonlite, sp, utils, xml2, devtools, knitr, rmarkdown, roxygen2, sf, testthat, Rcpp, &gt;= 3.2.4, *, *, *, *, *, &gt;= 0.12.4, *, *, *, *, *, *, *, *, *, *, *, \*      | C++11                   | Download and import of 'OpenStreetMap' ('OSM') data as 'sf' or 'sp' objects. 'OSM' data are extracted from the 'Overpass' web server and processed with very fast 'C++' routines for return to 'R'.                                                                                                                                                                                                                                                                                                                                                                                      | r        | packages | required | list(`-os` = "osx"), list(list(os = "linux", r = "release", dist = "trusty", env = "R\_CODECOV=true"), list(os = "linux", r = "devel", dist = "trusty"), list(os = "linux", r = "oldrel", dist = "trusty"), list(os = "osx", r = "release", before\_install = "", disable\_homebrew = TRUE))                  | jimhester/covr      | NA                                                                                                            | TRUE                  | list(on\_success = "change", on\_failure = "change") | Rscript -e "covr::codecov(line\_exclusions = list('src/rapidxml.h','src/rapidxml\_print.h'))" | NA                         | NA     | sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes, sudo apt-get --yes --force-yes update -qq, sudo apt-get install --yes libproj-dev libgeos-dev libgdal-dev libudunits2-dev                                   | NA                     | devtools    |

**Comment by maelle** [comment]
Not even sure such a collection (built from some R organizations) would make sense. 🤔 Maybe it'd be better to rely on community-contributed examples? Thoughts @jeroen @krlmlr?

If not it was at least a good `ghrecipes` exercise for me :joy:

**Comment by krlmlr** [comment]
This feels like a difficult problem, but if certain long texts/constructs are particularly frequent in `.travis.yml` files we might actually learn something ;-)

**Comment by maelle** [comment]
ahah so a tidy text analysis of their content tokenized by line would make sense.

but also a more complex tokenisation by different nesting levels 🤔

**Comment by maelle** [comment]
Archiving this repo as I do not have the opportunity to work on this package at the moment.

https://devguide.ropensci.org/curationpolicy.html#incubator-packages
