### ISSUE TITLE
Count votes?

### ISSUE THREAD

**Issue by krlmlr** [ropenscilabs/ghrecipes#6]
I've seen a few issues with a considerable number of votes in the dplyr repo. What's the best way to retrieve the issues most voted for?

**Comment by maelle** [comment]
oh nice one. I'll have a look. I think it'll involve iterating twice (issues, and then reactions).

I'm not sure one can ask for a number of reactions, that'd be cool, but I believe it'll first involve getting all reactions.

**Comment by maelle** [comment]
you'd want that only for opened issues right?

**Comment by maelle** [comment]
Hey by hand one can sort issues by reaction in a repo https://github.com/isaacs/github/issues/600, I had no idea! (but I'll still investigate the API solution of course)

**Comment by maelle** [comment]
https://github.com/tidyverse/dplyr/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by maelle** [comment]
😢 not possible here to directly sort issues by +1 https://developer.github.com/v4/enum/issueorderfield/

**Comment by krlmlr** [comment]
Awesome, I haven't even looked there! This solves the problem for me, feel free to close. A recipe would be even nicer, of course!

**Comment by maelle** [comment]
I got the query 😎 

```r
query{
  repository(owner: "tidyverse", name: "dplyr"){
    issues(first: 100, states: OPEN){
      edges{
        node{
          number
          title
          reactions(content: THUMBS_UP){
            totalCount
          }
        }
      }
    }
  }
}
```

recipe to come

**Comment by maelle** [comment]
@krlmlr what would you want by issue on top on their thumbs up count, title and issue number? a direct link, the body? should the function also filter for thumbs up count > 0?

**Comment by maelle** [comment]
maybe labels and assignees?

**Comment by krlmlr** [comment]
A link would be awesome, maybe the first paragraph (or 300 characters) of the body? Labels would be great, too.

A filter for count > 0 would be useful, that's the only thing I can't seem to do from the GUI. But that's easy enough to do when postprocessing.

How do we order by number of reactions?

**Comment by maelle** [comment]
> A link would be awesome, maybe the first paragraph (or 300 characters) of the body? Labels would be great, too.

oh and milestones?

How would you use the recipe, would you currently look at the output in say the viewer of RStudio? (I guess in the future different teams could build different dashboard based on recipes)

> How do we order by number of reactions?

I guess I could arrange by decreasing order before outputting the table. I could also add a parameter filter_null.

**Comment by krlmlr** [comment]
Thanks. Is the order still correct when you have `first: 100` in your query?

I'd run it in RStudio for now.

**Comment by maelle** [comment]
Oh in the actual recipe I'll iterate over all open issues, not only the first 100 :-)

Ok!

**Comment by maelle** [comment]
There's now `get_issues_thumbs`.

As you see I currently handle labels in a bad way because I don't know yet how to paste them together with a separator. I also need to add assignees. And tell me anything that's wrong 😉

**Comment by maelle** [comment]
Note: When R CMD check the package examples all fail because I apparently handle .onLoad badly, but other than that it should work.

**Comment by maelle** [comment]
Oh and I'm not sure how to make URL clickable from RStudio Viewer?

**Comment by krlmlr** [comment]
Thanks, works for me! I don't know about `jqr`, can't help with the labeling issue.   I'm amazed how concise you can express this query in that language.

Don't know about clickable URLs either.

I couldn't load the package without setting the `GITHUB_GRAPHQL_TOKEN` environment variable, could that explain the checking problem? I would make sure that loading always succeeds, though. It feels better to provide a way to reinitialize the ghql client. Currently `.onLoad()` adds `ghql_gh_cli` to the package environment directly; it might be better to put `ghql_gh_cli` into an environment that lives in your package environment.

**Comment by maelle** [comment]
> Thanks, works for me!

Thanks! No need for assignees in your case?

>  I'm amazed how concise you can express this query in that language.

I know right?! 

> Currently .onLoad() adds ghql_gh_cli to the package environment directly; it might be better to put ghql_gh_cli into an environment that lives in your package environment.

Yes I need to re-think the way I define the client. Now the check passes but see #10 

I could/should change the name of the environment variable because @jeroen told me it works with the usual `GITHUB_PAT`.

**Comment by maelle** [comment]
Reg having the clickable URL, I think one would only need to knit a report, in which the data.frame would be formatted like I do at the end of http://www.masalmon.eu/2018/03/04/hrbrpkgs/

**Comment by maelle** [comment]
Archiving this repo as I do not have the opportunity to work on this package at the moment.

https://devguide.ropensci.org/curationpolicy.html#incubator-packages
