### ISSUE TITLE
does one really need httr?

### ISSUE THREAD

**Issue by maelle** [ropenscilabs/ghrecipes#9]
cf https://github.com/maelle/ghrecipes/blob/9353ab06747ee7fa14f578c96658774132994451/R/zzz.R#L22 @sckott

**Comment by sckott** [comment]
`httr` is the http client used inside the pkg for now. so might as well use httr header fxn to do header construction. - the internal http functions just have `...` so the `headers` param doesn't automatically make a header object that httr wants, so user has to do that

**Comment by sckott** [comment]
open to any changes you think would make it better !

**Comment by maelle** [comment]
I guess it'd just be cool to use `crul` 😎
